#!/bin/bash


SCRIPT_DIR=$(readlink -m $(dirname $0))
OUT_DIR=$SCRIPT_DIR/out

export QT_HOME=$HOME/packages/qt-5.10.0/5.10.0/gcc_64


if [ $# -lt 1 ]; then
    WHAT_TO_MAKE=
elif [ $1 == "all" ]; then
    WHAT_TO_MAKE=
elif [ $1 == "app" ]; then
    WHAT_TO_MAKE=a.out.app
elif [ $1 == "exp" ]; then
    WHAT_TO_MAKE=a.out.exp
elif [ $1 == "gtest" ]; then
    WHAT_TO_MAKE=a.out.gtest
else
    echo "Must build either 'app', 'expp', 'gtest', or 'all'"
    exit 1
fi


if [ ! -e $OUT_DIR ]; then
    mkdir -p $OUT_DIR
fi


cd $OUT_DIR
cmake $SCRIPT_DIR


if [ $? -eq 0 ]; then
    make $WHAT_TO_MAKE
fi

